checked tests and debugged

diff --git a/quicktest-status b/quicktest-status
--- a/quicktest-status
+++ b/quicktest-status
@@ -1,46 +1,43 @@
-#!/bin/dash
-
-# This will show the list of all submissions as 
-# specified by <zid>
+#!/bin/bash
 
 PATH="$PATH:$(pwd)"
 
 # NOTE: this file contains all helper functions
-# which are used across different give scripts
+# which are used across different quicktest scripts
 . helpers.sh
 
-give_not_exist "give-status"
+quicktest_not_exist "quicktest-status"
 
 # check num args 
 if [ $# -ne 1 ]; then
-    echo "usage: give-status <zid>" >&2
+    echo "usage: quicktest-status <id>" >&2
     exit 1
 fi
 
-zid="$1"
+id="$1"
 
-# check invalid zid
-if ! echo "$zid" | grep -E '^z[0-9]{7}$' >/dev/null; then
-    echo "give-status: invalid zid: $zid" >&2
+# check invalid id
+if ! echo "$id" | grep -E '^z[0-9]{7}$' >/dev/null; then
+    echo "quicktest-status: invalid id: $id" >&2
     exit 1
 fi
 
-zid_match=0
-for assignment in .give/*; do
+id_match=0
+for assignment in .quicktest/*; do
     # check no assignments
     if ! [ -d "$assignment" ]; then
-        echo "no submissions for $zid"
+        echo "no submissions for $id"
         exit 0
     fi
     assignment_name="$(echo "$assignment" | cut -d '/' -f2,2)"
-    student="$(find "$assignment" -mindepth 1 -maxdepth 1 -type d | grep -E "$zid")" 2>/dev/null
-    # if no student could be found then iterate to the next assignment
+    version="$(find "$assignment" -mindepth 1 -maxdepth 1 -type d | grep -E "$id")" 2>/dev/null
+    # if no version could be found then iterate to the next assignment
     if [ $? -eq 1 ]; then
         continue
     fi    
-    zid_match=1
-    submissions="$(find "$student" -mindepth 1 -maxdepth 1 -type d | sort -n)" 2>/dev/null
-    num_submissions="$(find "$student" -mindepth 1 -maxdepth 1 -type d | wc -l)" 2>/dev/null
+    id_match=1
+    submissions="$(find "$version" -mindepth 1 -maxdepth 1 -type d | sort -n)" 2>/dev/null
+    num_submissions="$(find "$version" -mindepth 1 -maxdepth 1 -type d | wc -l)" 2>/dev/null
     echo "* $num_submissions submissions for $assignment_name"
 
     for submission in $submissions; do
@@ -59,7 +56,7 @@ for assignment in .give/*; do
     done
 done
 
-# no matching zid for all assignments
-if [ "$zid_match" -eq 0 ]; then
-    echo "no submissions for $zid"
+# no matching id for all assignments
+if [ "$id_match" -eq 0 ]; then
+    echo "no submissions for $id"
 fi
